### ISSUE TITLE
Can compression be supported?

### ISSUE THREAD

**Issue by hzm0603** [User344/NewWorldExplorer#1]
Can compression be supported?

**Comment by imunproductive** [comment]
What do you mean? Their custom compression is already supported and handled. Or are you talking about re-packing?

**Comment by imunproductive** [comment]
Re-packing will be added soon. I've already managed to re-pack and launch game with custom .pak file successfully, but right now I am making a GUI application to view, edit and re-pack everything with ease, but its my first experience with WPF so its not going as smooth as I planned. Hopefully I will find more free time soon to finish it.
