### ISSUE TITLE
It doesn't work properly. Can you update it?

### ISSUE THREAD

**Issue by hzm0603** [User344/NewWorldExplorer#2]
It doesn't work properly. Can you update it?

**Comment by imunproductive** [comment]
Can you be more specific? What exactly doesn't work? Maybe you get some exact error?

**Comment by hzm0603** [comment]
After the game version is updated, the Pak cannot be decompressed. The console window closes automatically one second after it appears.

**Comment by imunproductive** [comment]
I just checked on the last game version and it works like a charm. Are you sure you are running it correctly? You have to run it from cmd, with an argument as the game's path.

Example: NewWorldExplorerCLI.exe "C:\Program Files\Steam\steamapps\common\New World"

**Comment by hzm0603** [comment]
Thank you very much. It's working normally.

**Comment by hzm0603** [comment]
Can you tell me your discord?

**Comment by hzm0603** [comment]
I want to learn something from you. I am willing to pay money

**Comment by imunproductive** [comment]
Glad it worked.
